name: hrea_mobile_staff
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter:
    sdk: flutter
  pinput: ^3.0.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  lottie: ^2.6.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - animations/
