name: hrea_mobile_staff
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter:
    sdk: flutter
  pinput: ^3.0.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  lottie: ^2.6.0
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.0
  intl:
  expandable_text: ^2.3.0
  image_picker: ^1.0.4
  get_storage: ^2.1.1
  # awesome_dialog: ^3.1.0
  flutter_quill: ^7.6.1
  flutter_quill_extensions: ^0.5.0
  calendar_date_picker2:
  firebase_messaging: ^14.2.3
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.4.1
  flutter_spinkit: ^5.2.0
  socket_io_client: ^2.0.3+1
  file_picker: ^6.0.0
  open_file:
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  # flutter_localization: ^0.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - animations/
